In [3]:
import numpy as np

electricity = np.array([
    [120, 130, 125, 140, 150, 160, 155],
    [100, 110, 105, 115, 120, 130, 125],
    [90,  95,  100, 98,  105, 110, 108],
    [140, 145, 150, 155, 160, 165, 170]
])


Part A

In [3]:
electricity = np.random.randint(120, 651, size=(4, 7))
print(electricity)

[[555 515 306 214 256 220 121]
 [459 540 399 633 397 240 167]
 [251 239 160 604 207 189 353]
 [640 361 150 359 197 594 476]]


In [4]:
print("Shape:", electricity.shape)
print("Number of dimensions:", electricity.ndim)
print("Total number of elements:", electricity.size)
print("Data type:", electricity.dtype)

Shape: (4, 7)
Number of dimensions: 2
Total number of elements: 28
Data type: int32


Part B

In [4]:
avg_per_hostel = np.mean(electricity, axis=1)
print("Average electricity per hostel:", avg_per_hostel)


Average electricity per hostel: [140.         115.         100.85714286 155.        ]


In [5]:
max_per_hostel = np.max(electricity, axis=1)
print("Maximum electricity per hostel:", max_per_hostel)


Maximum electricity per hostel: [160 130 110 170]


In [6]:
highest_avg_hostel = np.argmax(avg_per_hostel)
print("Hostel with highest average usage:", highest_avg_hostel)


Hostel with highest average usage: 3


In [7]:
print("Hostel with highest average usage: Hostel", highest_avg_hostel + 1)


Hostel with highest average usage: Hostel 4


Part B2

In [8]:
total_per_day = np.sum(electricity, axis=0)
print("Total electricity per day:", total_per_day)


Total electricity per day: [450 480 480 508 535 565 558]


In [9]:
highest_day = np.argmax(total_per_day)
print("Day with highest total consumption: Day", highest_day + 1)


Day with highest total consumption: Day 6


Part C

In [12]:
import numpy as np

usage = np.array([
    [500, 600, 450, 700],
    [480, 520, 610, 580],
    [530, 490, 560, 620]
])


In [13]:
penalized_usage = np.where(usage > 550, usage * 1.20, usage)

print("Penalized Usage:")
print(penalized_usage)


Penalized Usage:
[[500. 720. 450. 840.]
 [480. 520. 732. 696.]
 [530. 490. 672. 744.]]


Part D

In [16]:
avg = np.mean(usage, axis=1, keepdims=True)


In [17]:
comparison = usage > avg


In [19]:
print("Averages:\n", avg)
print("Comparison:\n", comparison)

Averages:
 [[562.5]
 [547.5]
 [550. ]]
Comparison:
 [[False  True False  True]
 [False False  True  True]
 [False False  True  True]]


Part E1

In [21]:
# reshaped1 = usage.reshape(1, 28)
# or
reshaped1 = usage.reshape(1, -1)


Part E2

In [23]:
reshaped2 = usage.reshape(2, -1)


Part F

In [24]:
electricity[0,0] = 999
