In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
mat=np.array([1,2,3],[4,5,6])
print(mat)

In [ ]:
mat=np.array([[1,2,3],[4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.arrange(0,10)

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Array Properties

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])

In [ ]:
print(arr.ndim)  #Dimensions
print(arr.shape) #Rows , Columns
print(arr.size)  #Total elements
print(arr.dtype)

2
(2, 3)
6
int64


Type Conversions

In [ ]:
arr=np.array([1.2,2.5,3.7])
arr_int = arr.astype(int)
print(arr_int)

[1 2 3]


Indexing and Slicing

In [ ]:
arr=np.array([10,20,30,40])
print(arr[0])#indexing
print(arr[-1])

10
40


In [ ]:
print(arr[1:3])
print(arr[:2])
print(arr[::2])

[20 30]
[10 20]
[10 30]


2D Indexing


In [ ]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[0,1])
print(mat[1])

2
[4 5 6]


In [ ]:
print(mat[:, 1])   #column1

[2 5 8]


In [ ]:
a=np.array([1,2,3])
b=a #this logic is not safe
b[0]=99
print(a)

[99  2  3]


In [ ]:
a=np.array([1,2,3])
b=a.copy()#copy
b[0]=99
print(a)
print(b)

[1 2 3]
[99  2  3]


Basic Array Operations(VECTOR POWER
)

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Scalar Operations

In [ ]:
print(a+18)
print(a*2)

[19 20 21]
[2 4 6]


unfus (universal functions)

In [ ]:
arr=np.array([1,4,9,16])

print(np.sqrt(arr))
print(np.long(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))

[1. 2. 3. 4.]
[ 1  4  9 16]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
16
1
7.5
30
5.678908345800274


Boolean Indexing


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [ ]:
print(arr>25)

[False False  True  True  True]


Broadcasting Rule

In [ ]:
#Numpy automatially broadcasting

In [5]:
arr = np.array([1,2,3,4])
print(arr+10)

[11 12 13 14]


In [6]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat+10)

[[11 12 13]
 [14 15 16]]


In [7]:
row = np.array([1,2,3])
print(mat+row)

[[2 4 6]
 [5 7 9]]


Matrix Multiplication

In [8]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [9]:
print(A.T) #Transpose

[[1 3]
 [2 4]]


Random Module

In [10]:
np.random.rand(5)

array([0.06945655, 0.76349933, 0.86109272, 0.52705215, 0.94011298])

In [11]:
np.random.rand(3,3)

array([[0.8865675 , 0.33341202, 0.4782234 ],
       [0.65537885, 0.11355737, 0.46357079],
       [0.82312677, 0.51667002, 0.88844134]])

In [ ]:
np.random.randint(1,100,10) #10 is no. of elements , 1 is starting point , 100 end point

array([83, 20, 27, 27, 52,  4, 98, 44, 82, 23], dtype=int32)

Reshaping Arrays

In [14]:
arr=np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Axis in NumPy

In [15]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:
print(np.sum(arr))

21


In [17]:
print(np.sum(arr,axis=0)) #Column Wise

[5 7 9]


In [ ]:
print(np.sum(arr,axis=1)) #row wise

[ 6 15]


Where in NumPy

In [19]:
arr=np.array([10,-5,20,-3,15])


In [20]:
result = np.where(arr<0,0,arr)
print(result)

[10  0 20  0 15]


In [21]:
arr=np.array([1,2,3,4,5])

In [22]:
result = np.where(arr%2 != 0, -1, arr)
print(result)

[-1  2 -1  4 -1]


In [23]:
marks = np.array([45,78,32,90,55])


In [25]:
status = np.where(marks>=50,1,0)
print(status)

[0 1 0 1 1]


In [26]:
data = np.array([10,20,30,40,50])

In [ ]:
mean_val = np.mean(data)
result = np.where(data > mean_val , mean_val , data) #1 parameter is condn , 2nd is true value , 3rd false value
print(result)

[10. 20. 30. 30. 30.]


Applying (Where) condition in 2d array

In [28]:
mat = np.array([[10,60,30] , [80,20,30]])

In [29]:
result = np.where(mat >= 50, 1, 0)
print(result)

[[0 1 0]
 [1 0 0]]
